### ISSUE TITLE
Uploadcare widget does not send data to form

### ISSUE THREAD

**Issue by kennethpdev** [uploadcare/uploadcare-jotform-widget#16]
Hi, I'm a JotForm developer. Please check this particular [issue](https://www.jotform.com/answers/1456126), the widget does not send data to form after an image was cropped and clicked "Done". Thus condition or the submit says the widget is empty.

One of the support created a  test [form](https://form.jotform.com/81161780462960). You can see the replication posted by **BJoanna**.

Regards,

**Comment by dmitry-mukhin** [comment]
@kenma9123 we can't see the issue via that link

**Comment by kennethpdev** [comment]
Sorry I didn't knew it was private. But you can at least test the form. Take a look at [this ](https://www.jotform.com/uploads/forum/BJoanna/1524808872upload.gif) replication demo.

**Comment by nd0ut** [comment]
@kenma9123 Thank you for the feedback!

We will release the fix in a couple of days. I'll let you know when it's done.

**Comment by nd0ut** [comment]
@kenma9123 I've linked PR related to your issue. It should be checked by reviewer before release. 
I will try to have it merged tomorrow. 

Thanks for waiting.

**Comment by nd0ut** [comment]
@kenma9123 the fix is in production. Seems to work right now. Check it please.

**Comment by kennethpdev** [comment]
@nd0ut yup we can confirm that. Thank you for the fix.
